name: Release Test

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm test
      
      - name: Check package validity
        run: npm pack --dry-run
      
      - name: Validate version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          GITHUB_REF_VERSION=${GITHUB_REF#refs/tags/v}
          
          echo "Package version: $PACKAGE_VERSION"
          echo "GitHub release version: $GITHUB_REF_VERSION"
          
          if [ "$PACKAGE_VERSION" != "$GITHUB_REF_VERSION" ]; then
            echo "Error: Package version ($PACKAGE_VERSION) does not match GitHub release version ($GITHUB_REF_VERSION)"
            exit 1
          fi
